export const ALL_NOTES_REQUEST = "ALL_NOTES_REQUEST";
export const ALL_NOTES_SUCCESS = "ALL_NOTES_SUCCESS";
export const ALL_NOTES_FAIL = "ALL_NOTES_FAIL";

export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAIL = "CREATE_NOTE_FAIL";

export const UPDATE_NOTE_REQUEST = "CREATUPDATE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "CREATUPDATE_SUCCESS";
export const UPDATE_NOTE_FAIL = "CREATUPDATE_FAIL";
